ALTER TABLE orcamentos ADD COLUMN IF NOT EXISTS valor_original NUMERIC(10,2);
ALTER TABLE orcamentos ADD COLUMN IF NOT EXISTS revisao_numero INTEGER DEFAULT 0;
ALTER TABLE orcamentos ADD COLUMN IF NOT EXISTS revisado_em TIMESTAMPTZ;
